using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Gasci.Core;
using Gasci.Variables;

namespace Gasci.Layout;

/// <summary>Size of a text in characters (every tile font is monospaced: one character = one cell at scale 1).</summary>
public readonly record struct TextMetric(int Natural, int Min, int Lines)
{
    public static TextMetric Max(TextMetric a, TextMetric b) =>
        new(Math.Max(a.Natural, b.Natural), Math.Max(a.Min, b.Min), Math.Max(a.Lines, b.Lines));
}

/// <summary>
/// Precomputed sizes of every text key: the width of its longest line (natural), of its longest word
/// (the narrowest it can wrap to) and its number of lines, per language and the maximum across
/// languages (menus measure with the maximum, so they keep their size when the language changes).
/// --validate writes them to assets/data/generated/text_metrics.csv together with a hash of the
/// files they depend on; if the hash does not match at start-up, they are computed in memory and a
/// warning is logged.
/// </summary>
public sealed class TextMetrics
{
    private const string HashPrefix = "# source-sha256:";

    private readonly Dictionary<string, Dictionary<string, TextMetric>> _byKey = new();
    private readonly Dictionary<string, TextMetric> _max = new();

    public bool IsFromFile { get; private set; }

    /// <summary>Widest translation of a key (zero for unknown keys).</summary>
    public TextMetric Get(string key) => _max.GetValueOrDefault(key);

    public TextMetric Get(string key, string language) =>
        _byKey.TryGetValue(key, out var byLanguage) && byLanguage.TryGetValue(language, out TextMetric m) ? m : Get(key);

    public IEnumerable<string> Keys => _max.Keys;

    // ---- Computing -----------------------------------------------------------------------

    public static TextMetric Measure(string text)
    {
        string plain = TextLayout.Strip(text, VariableWidth);
        string[] lines = plain.Split('\n');
        int natural = lines.Max(l => l.TrimEnd().Length);
        int min = lines.SelectMany(l => l.Split(' ', StringSplitOptions.RemoveEmptyEntries)).Select(w => w.Length).DefaultIfEmpty(0).Max();
        return new TextMetric(natural, min, lines.Length);
    }

    private static int VariableWidth(string name) => VariableRegistry.Find(name)?.MaxTextWidth ?? 0;

    public static TextMetrics Compute(Localization loc)
    {
        var metrics = new TextMetrics();
        foreach (string key in loc.Keys)
            foreach (string language in loc.Languages)
                if (loc.HasLanguage(key, language))
                    metrics.Add(key, language, Measure(loc.Get(key, language)));
        return metrics;
    }

    private void Add(string key, string language, TextMetric metric)
    {
        if (!_byKey.TryGetValue(key, out var byLanguage)) _byKey[key] = byLanguage = new();
        byLanguage[language] = metric;
        _max[key] = _max.TryGetValue(key, out TextMetric current) ? TextMetric.Max(current, metric) : metric;
    }

    // ---- Files ---------------------------------------------------------------------------

    /// <summary>Hash of the files the metrics depend on: the texts and the variable templates ({v:} widths).</summary>
    public static string SourceHash(string assetsFolder)
    {
        using var sha = SHA256.Create();
        string data = Path.Combine(assetsFolder, "data");
        var files = new List<string> { Path.Combine(data, "dialogs.csv") };
        string variables = Path.Combine(data, "variables");
        if (Directory.Exists(variables)) files.AddRange(Directory.GetFiles(variables, "*.json").Order(StringComparer.Ordinal));
        foreach (string file in files.Where(File.Exists))
        {
            byte[] bytes = File.ReadAllBytes(file);
            sha.TransformBlock(bytes, 0, bytes.Length, null, 0);
        }
        sha.TransformFinalBlock([], 0, 0);
        return Convert.ToHexString(sha.Hash!);
    }

    public static string? StoredHash(string file)
    {
        if (!File.Exists(file)) return null;
        string? first = File.ReadLines(file).FirstOrDefault();
        return first is not null && first.StartsWith(HashPrefix) ? first[HashPrefix.Length..].Trim() : null;
    }

    public void Write(string file, string hash)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(file)!);
        var text = new StringBuilder();
        text.AppendLine(HashPrefix + hash);
        text.AppendLine("# Generated by --validate. Do not edit: run `dotnet run --project src/Gasci -- --validate` after changing texts.");
        text.AppendLine("key,language,natural,min,lines");
        foreach (var (key, byLanguage) in _byKey.OrderBy(k => k.Key, StringComparer.Ordinal))
            foreach (var (language, m) in byLanguage.OrderBy(l => l.Key, StringComparer.Ordinal))
                text.AppendLine($"{key},{language},{m.Natural},{m.Min},{m.Lines}");
        File.WriteAllText(file, text.ToString());
    }

    public static TextMetrics Read(string file)
    {
        var metrics = new TextMetrics { IsFromFile = true };
        foreach (string line in File.ReadLines(file))
        {
            if (line.StartsWith('#') || line.StartsWith("key,")) continue;
            string[] f = line.Split(',');
            if (f.Length != 5) continue;
            metrics.Add(f[0], f[1], new TextMetric(
                int.Parse(f[2], CultureInfo.InvariantCulture), int.Parse(f[3], CultureInfo.InvariantCulture), int.Parse(f[4], CultureInfo.InvariantCulture)));
        }
        return metrics;
    }

    /// <summary>Reads the generated file if it is up to date; otherwise computes the metrics and logs a warning.</summary>
    public static TextMetrics Load(Localization loc)
    {
        string file = Paths.TextMetricsFile;
        string hash = SourceHash(Paths.Assets);
        if (StoredHash(file) == hash)
        {
            try { return Read(file); }
            catch (Exception e) { Log.Warn($"text_metrics.csv could not be read ({e.Message}); measuring the texts at start-up"); }
        }
        else Log.Warn("text_metrics.csv is missing or out of date; measuring the texts at start-up (run --validate to regenerate it)");
        return Compute(loc);
    }
}
